tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  sodalite.nodes.Configuration.ruleset:
    derived_from: tosca.nodes.SoftwareComponent
    description: Node for registration/deregistration of the ruleset file
    properties:
      ruleset:
        type: list
        description: ruleset list with rules to register
        required: True
      dest:
        type: string
        description: IP address of the ruleserver
        required: True
      id: 
        type: string
        description: name of the ruleset to register
        required: True
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            inputs:
              ruleset: { default: { get_property: [ SELF, ruleset ] }, type: string }
              dest:    { default: { get_property: [ SELF, dest ] }, type: string }
              id:      { default: { get_property: [ SELF, id ] }, type: string }
            implementation:
              primary: playbooks/ruleset_register.yml
              dependencies:
                - playbooks/ruleset.yml.j2

          delete:
            inputs:
              dest:    { default: { get_property: [ SELF, dest ] }, type: string }
              id:      { default: { get_property: [ SELF, id ] }, type: string }
            implementation:
              primary: playbooks/ruleset_deregister.yml
              