tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - ruleset.config.yml

topology_template:

  inputs:
    ruleserver_address:
      type: string
    monitoring_id:
      type: string
    ruleset:
      type: list
    
  node_templates:

    rule-config:
      type: sodalite.nodes.Configuration.ruleset
      properties:
        ruleset: { get_input: ruleset }
        ruleserver_address: { get_input: ruleserver_address }
        monitoring_id: { get_input: ruleset_id }
