global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files: []

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - {targets: ['localhost:9090']}

  - job_name: openstack
    scheme: http
    openstack_sd_configs:
      - {identity_endpoint: 'https://cloud.sodalite.eu:5000/v3/', username: mario, project_name: ochestrator, password: 'yourpassword', rol
e: instance, domain_name: default, project_id: '0f3710f7dc4341f388f5df59cdb62b6a', port: 9100}
    relabel_configs:
        # Keep only instances which are flagged for scraping
      - {source_labels: [__meta_openstack_tag_prometheus_io_scrape], action: keep, regex: 'true'}
      # Commented to use the private IPs
      - {source_labels: [__meta_openstack_public_ip, __meta_openstack_tag_prometheus_io_port], action: replace, regex: '([^:]+)(?::\d+)?;
(\d+)', replacement: '$1:$2', target_label: __address__}
      #- {source_labels: [__address__, __meta_openstack_tag_prometheus_io_port], action: replace, regex: '([^:]+)(?::\d+)', replacement:
'$1:$2', target_label: __address_}
      - {source_labels: [__meta_openstack_instance_name], target_label: instance}

  - job_name: skydive
    scrape_interval: 5s
    static_configs:
            - targets: ['localhost:9080']

  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['154.48.185.205:9100']