---
- hosts: localhost
  gather_facts: no

  tasks:
    
    - name: Deregister rule file in ruleserver
      shell: curl -X DELETE http://{{ ruleserver_address|quote }}:9092/rules/{{ ruleset_id }}
...