groups:
- name: alert.rules
  rules:
  - alert: HostHighCpuLoad
    expr: 100 - (avg by(instance,os_id) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host high CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: HostLowCpuLoad
    expr: 100 - (avg by(instance,os_id) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) < 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host low CPU load (instance {{ $labels.instance }})"
      description: "CPU load is < 20%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
